version: 2.1
executors:
  node_executor:
    docker:
      - image: circleci/node:8.11.2
    working_directory: /tmp/authorization360
jobs:
  build:
    executor: node_executor
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: yarn install
      - persist_to_workspace:
          root: /tmp/authorization360
          paths:
            - node_modules
  unit_test:
    executor: node_executor
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/authorization360
      - run:
          name: Run unit tests
          command: yarn test:unit
  e2e_test:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: yarn install
      - run:
          name: Run tests
          command: yarn test:e2e -- --headless

workflows:
  version: 2
  full_tests:
    jobs:
      - build
      - unit_test:
          requires:
            - build
      - e2e_test:
          requires:
            - build